---
- name: Destroing
  block:
  - name: Destroy infrastructure
    environment: "{{ default_variables }}"
    terraform:
      state: absent
      force_init: true
      project_path: "{{ terraform_remote_dir }}/{{ scenario_name }}"
      backend_config:
        key: "terraform_state/{{ scenario_name }}"
        bucket: "obs-csm"
        region: "eu-de"
      variables: "{{ tf_variables }}"
  - name:  Remove terraform directory
    file:
      path: "/tmp/{{ item }}"
      state: absent
    with_fileglob:
      - /tmp/*
