---
- name: Download or create shared private key
  block:
  - name: Download/create key  # noqa 301 - get_key is more or less idempotent
    environment: "{{ default_variables }}"
    script: "get_key.py --output {{ key_path }} --key key/{{ key_name }}"
    args:
      executable: python3
    register: get_key_output
    changed_when: get_key_output == 'Private key is up to date\n'
