---
- name: Converge
  hosts: instance
  vars:
    requirements: "requirements.txt"
    scenario_name: "scenario1"
    key_name: "key_scenario1"
    infra_state: present
    terraform_version: "0.12.20"
  roles:
    - role: anton_sidelnikov.terraform
    - role: build_infrastructure
